// Viewer of testbench data generated by
// library for course A0B35SPS - Structures of Computers System
// CTU-FFE Prague, Czech Republic 
// Department of Control Eng. 
// Author: Richard Susta
// Published under GNU General Public License
////////////////////////////////////////////////////////////////


using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Windows.Forms;

namespace FpgaLcdUtils
{
    public partial class TBFormHelp : Form
    {
        public TBFormHelp()
        {
            InitializeComponent();
        }
                private void FormHelp_Load(object sender, EventArgs e)
        {
            try
            {
                // load RTF help file stored in resources
                  richTextBoxHelp.Rtf = FpgaLcdUtils.Properties.Resources.Help;
            }
            catch (Exception ex)
            {
                richTextBoxHelp.Text = ex.Message;
            }
        }

        private void button1_Click(object sender, EventArgs e)
        {
            Close();
        }

    }
}
